#!/bin/sh

# ==============================================================================
# Configuration
# ==============================================================================

PROJECT_ROOT="$(pwd)"
BIN_DIR="${PROJECT_ROOT}/bin"

# Arch Linux standard paths for UEFI Firmware (OVMF)
# Note: Arch now uses 4MB images by default (.4m.fd)
OVMF_CODE="/usr/share/edk2/x64/OVMF_CODE.4m.fd"
OVMF_VARS="/usr/share/edk2/x64/OVMF_VARS.4m.fd"

# S4 image generated by generator/main.py
S4IMG_FILE="${BIN_DIR}/s4_image.bin"

# The target UEFI application built by 'build_uefi.sh'
EFI_FILE="${BIN_DIR}/Activator.efi"

# Output Disk Image
DISK_IMG="${BIN_DIR}/disk.img"

# Partition Layout Constants
# Align everything to 1MB (2048 sectors * 512 bytes) for simplicity
SECTOR_SIZE=512
ESP_START_SECTOR=2048             # 1MB
ESP_SIZE_MB=64
ESP_SIZE_SECTORS=$((ESP_SIZE_MB * 1024 * 1024 / SECTOR_SIZE))

# Swap starts right after ESP
SWAP_START_SECTOR=$((ESP_START_SECTOR + ESP_SIZE_SECTORS))

# ==============================================================================
# Pre-flight Checks
# ==============================================================================

if [ ! -f "$S4IMG_FILE" ]; then
    echo "Error: Binary not found at $S4IMG_FILE"
    echo "Please run 'python3 generator/main.py' first."
    exit 1
fi

if [ ! -f "$EFI_FILE" ]; then
    echo "Error: Binary not found at $EFI_FILE"
    echo "Please run './scripts/build_uefi.sh' first."
    exit 1
fi

if [ ! -f "$OVMF_CODE" ]; then
    echo "Error: OVMF firmware not found at $OVMF_CODE"
    echo "Please install 'edk2-ovmf' via pacman."
    exit 1
fi

if ! command -v sgdisk &> /dev/null; then
    echo "Error: 'sgdisk' not found. Please install 'gptfdisk'."
    echo "  sudo pacman -S gptfdisk"
    exit 1
fi

if ! command -v mformat &> /dev/null; then
    echo "Error: 'mtools' not found. Please install it."
    echo "  sudo pacman -S mtools"
    exit 1
fi

mkdir -p "$BIN_DIR"

# ==============================================================================
# Disk Image Creation
# ==============================================================================

echo "========================================"
echo "Fabricating Disk Image ($DISK_IMG)..."

# 1. Create a blank 512MB disk image
# We use dd to create a sparse file quickly
dd if=/dev/zero of="$DISK_IMG" bs=1M count=512 status=none

# 2. Partitioning with sgdisk (GPT)
# -o: Clear partition table
# -n: New partition (num:start:end)
# -t: Type code (EF00 = EFI System, A502 = FreeBSD Swap)
# -c: Partition name
sgdisk -o \
    -n 1:$ESP_START_SECTOR:+$((ESP_SIZE_MB))M -t 1:EF00 -c 1:"EFI System" \
    -n 2:$SWAP_START_SECTOR:0              -t 2:A502 -c 2:"FreeBSD Swap" \
    "$DISK_IMG" > /dev/null

echo "  -> GPT Table created."
echo "     P1: ESP  (Start: ${ESP_START_SECTOR}s, Size: ${ESP_SIZE_MB}MB)"
echo "     P2: SWAP (Start: ${SWAP_START_SECTOR}s, Type: FreeBSD Swap)"

# ==============================================================================
# Partition 1: EFI System Partition (FAT32)
# ==============================================================================
# Calculate byte offset for mtools
# mtools allow accessing a partition inside an image using '@@offset' syntax
ESP_OFFSET_BYTES=$((ESP_START_SECTOR * SECTOR_SIZE))

# 1. Format P1 as FAT32
mformat -i "${DISK_IMG}@@${ESP_OFFSET_BYTES}" -F ::

# 2. Create Directory Structure
mmd -i "${DISK_IMG}@@${ESP_OFFSET_BYTES}" ::/EFI
mmd -i "${DISK_IMG}@@${ESP_OFFSET_BYTES}" ::/EFI/BOOT

# 3. Install Activator as Bootloader
mcopy -i "${DISK_IMG}@@${ESP_OFFSET_BYTES}" "$EFI_FILE" ::/EFI/BOOT/BOOTX64.EFI

echo "  -> Activator installed to ESP."

# ==============================================================================
# Partition 2: FreeBSD Swap (Raw Write)
# ==============================================================================

# We write the S4 image directly to the start of the Swap partition.
# This aligns with our C code which reads from LBA 0 relative to the partition handle.
echo "  -> Writing S4 Image to Swap Partition..."

dd if="$S4IMG_FILE" of="$DISK_IMG" \
   bs="$SECTOR_SIZE" seek="$SWAP_START_SECTOR" \
   conv=notrunc status=none

echo "========================================"
echo "Starting QEMU..."
echo "========================================"

# ==============================================================================
# QEMU Execution
# ==============================================================================

# -drive file="$DISK_IMG",format=raw: Connect our GPT disk image as a raw hard drive
# Note: We removed the 'fat:rw:...' argument.

qemu-system-x86_64 \
    -m 512M \
    -drive if=pflash,format=raw,readonly=on,file="$OVMF_CODE" \
    -drive if=pflash,format=raw,readonly=on,file="$OVMF_VARS" \
    -drive file="$DISK_IMG",format=raw \
    -nographic \
    -net none